name: Update Release Tags
on:
  push:
    tags: ['*']
jobs:
  update-release-tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./ # update-action-release-tags
