name: Update Release Tags
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  update-release-tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: bewuethr/release-tracker-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          update-latest: true
